### ISSUE TITLE
链接为`[](.md#)`时无效

### ISSUE THREAD

**Issue by byronogis** [tcatche/hexo-filter-link-post#1]
- `[](target.md)`, 这样是没问题的
- `[](target.md#标题)`, 这样的形式就不会生效了

**Comment by tcatche** [comment]
> * `[](target.md)`, 这样是没问题的
> * `[](target.md#标题)`, 这样的形式就不会生效了

更新了 `1.0.1` 版本，试一下呢

**Comment by byronogis** [comment]
> > * `[](target.md)`, 这样是没问题的
> > * `[](target.md#标题)`, 这样的形式就不会生效了
> 
> 更新了 `1.0.1` 版本，试一下呢

没问题啦😁
